### ISSUE TITLE
npm v0.0.8 seems out of sync with github

### ISSUE THREAD

**Issue by aaronmccall** [sethmcl/chrome-mock#2]
Line 158 of lib/chrome/Tabs.js in the npm installed version reads as follows:
```javascript
      callback([{id: 0, id: 1}]);
```

whereas the corresponding [line on github](https://github.com/sethmcl/chrome-mock/blob/master/lib/chrome/Tabs.js#L158) reads:
```javascript
      callback([{id: 0}]);
```

**Comment by Klowner** [comment]
Time for a an 0.0.9 release with i18n and storage support? :tada:

**Comment by sethmcl** [comment]
Release 0.0.9 today. Let me know if you see any issues!
